# Generated by Django 5.2.1 on 2025-06-04 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('test_type', models.CharField(blank=True, max_length=128, null=True)),
                ('testing_by', models.CharField(blank=True, max_length=128, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('base_url', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('role', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManualTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('preconditions', models.TextField(blank=True, null=True)),
                ('steps', models.TextField(blank=True, null=True)),
                ('expected', models.TextField(blank=True, null=True)),
                ('actual', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('priority', models.CharField(blank=True, max_length=32, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=128, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_test_cases', to='main_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('endpoint', models.CharField(blank=True, max_length=256, null=True)),
                ('method', models.CharField(blank=True, max_length=16, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_url', models.CharField(blank=True, max_length=256, null=True)),
                ('request_body_template', models.TextField(blank=True, null=True)),
                ('headers', models.TextField(blank=True, null=True)),
                ('query_params', models.TextField(blank=True, null=True)),
                ('path_params', models.TextField(blank=True, null=True)),
                ('expected_status_code', models.IntegerField(blank=True, null=True)),
                ('last_run_status', models.CharField(default='Not Run', max_length=32)),
                ('last_run_status_code', models.IntegerField(blank=True, null=True)),
                ('last_run_response_time', models.FloatField(blank=True, null=True)),
                ('last_run_response_body', models.TextField(blank=True, null=True)),
                ('last_run_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_scripts', to='main_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='APIManualTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=64)),
                ('test_case', models.CharField(max_length=256)),
                ('request_type', models.CharField(blank=True, max_length=16, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=256, null=True)),
                ('request', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('assertion_type', models.CharField(blank=True, max_length=64, null=True)),
                ('expected_status', models.CharField(blank=True, max_length=64, null=True)),
                ('to_replace', models.CharField(blank=True, max_length=256, null=True)),
                ('add_to_context_value', models.CharField(blank=True, max_length=256, null=True)),
                ('add_to_context_key', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_manual_test_cases', to='main_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='completed', max_length=32)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('quality_score', models.IntegerField(blank=True, null=True)),
                ('coverage_score', models.IntegerField(blank=True, null=True)),
                ('execution_score', models.IntegerField(blank=True, null=True)),
                ('success_score', models.IntegerField(blank=True, null=True)),
                ('env', models.CharField(default='Dev', max_length=32)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='main_app.project')),
            ],
        ),
    ]
